"""Original worked examples and bounded personal-lab catalog; no assessment keys."""
LABS = {
    'threat': {'week': 1, 'title': 'Trust boundaries · notes and files'},
    'injection': {'week': 4, 'title': 'SQL and command injection'},
    'xss': {'week': 5, 'title': 'Client-side injection'},
    'auth': {'week': 6, 'title': 'JWT and object authorization'},
    'api-bad': {'week': 10, 'title': 'API · vulnerable'},
    'api-good': {'week': 10, 'title': 'API · defended'},
    'ai-bad': {'week': 14, 'title': 'AI policy mock · vulnerable'},
    'ai-good': {'week': 14, 'title': 'AI policy mock · defended'},
    'ops-bad': {'week': 15, 'title': 'Release service · fail-open'},
    'ops-good': {'week': 15, 'title': 'Release service · fail-closed'},
    'project': {'week': 16, 'title': 'NoteVault · personal project rehearsal'},
}

# Each case states a concrete observation, its mechanism and a falsifiable next test.
CASES = [
 ('A filename crosses a boundary', 'A notes service accepts a filename from a browser. A developer joins it to an uploads directory and assumes that join confines the result. An input containing parent-directory segments can change the resolved location. Trace the canonical path, the storage boundary and the operation that consumes it.', 'A path join is not a containment check.', 'Draw browser, application and file store. Test a normal filename, parent segments and an absolute path inside your own disposable lab. State which resolved paths must be rejected.', 'How would a symbolic link change a check performed before opening a file?', 'Threat model → trust boundary → canonical destination → permitted operation', 'https://cheatsheetseries.owasp.org/cheatsheets/Threat_Modeling_Cheat_Sheet.html'),
 ('One defect, three signals', 'A static scanner flags an unchecked copy, a fuzzer finds a crash, and a dependency scanner flags an unrelated package. Group the first two by root cause and source location. A dependency version match needs reachability and deployment context before its priority is compared with the reproduced crash.', 'Three findings need not mean three distinct bugs.', 'Build an error log with source location, trigger, impact hypothesis and one regression input. Rerun the same check after the patch.', 'Which source changes require a fresh result rather than reusing a cached scan?', 'Commit → independent signals → reproduce → root cause → regression', 'https://llvm.org/docs/LibFuzzer.html'),
 ('Encryption can preserve structure', 'Repeated plaintext blocks under ECB produce repeated ciphertext blocks for the same key. A mode that hides this repetition still needs an integrity design: confidentiality alone does not tell a receiver whether a message was changed. Compare the visible pattern with an authenticated-decryption failure.', 'Random-looking ciphertext does not prove authenticity.', 'Change repeated input blocks in the AES model, then explain which observation concerns confidentiality and which check concerns tampering.', 'What goes wrong if an authenticated-encryption nonce repeats under one key?', 'Plaintext blocks → encryption mode → ciphertext → integrity decision', 'https://csrc.nist.gov/pubs/sp/800/38/d/final'),
 ('Data changes the parser', 'Compare building a SQL query by concatenating a name with binding that same name as a parameter. In the first case an input can become query syntax. In the second it remains a value. Escaping for SQL does not protect a later operating-system command built from the same value.', 'Validation must match the interpreter that eventually consumes the value.', 'Use your personal injection target. Save a benign baseline and one changed input, then identify the SQL or shell boundary and retest the matching defense.', 'Why does using a shell-free argument array change the command-injection threat model?', 'Input → query or command construction → parser → privileged operation', 'https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html'),
 ('A safe string in the wrong context', 'A value encoded for an HTML text node may later be inserted into a script or URL attribute. The destination determines the needed control. A stored script can execute with the origin of the page that later renders it, even if the original submitter is gone.', 'Escaping is contextual; origin privileges follow the rendered page.', 'Compare all four sinks in the XSS context model. Use harmless visible markers in your own personal target, and explain the effect of a text-only rendering fix.', 'How do CSP, HttpOnly cookies and output encoding address different parts of the attack?', 'Stored input → output context → browser parser → origin authority', 'https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html'),
 ('Who owns this order?', 'Alice signs in successfully and requests an order owned by Bob. Authentication answers who made the request; authorization must still compare that subject with the requested object and operation. An unverified JWT payload is a claim from the caller, not a trusted identity.', 'A valid session does not grant access to every object.', 'Record a normal request, an unauthenticated request, a wrong-owner request and a permitted-owner request. Compare the status and response body after the repair.', 'What must change when authorization rules include organization membership and delegated roles?', 'Credential → verified subject → action/object policy → response', 'https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html'),
 ('Review by explaining the miss', 'A learner repeats an injection challenge until the payload is familiar but still cannot explain why it changes a query. Reclassify the failure as a parser-model gap, use a different input and explain the before/after query structure without notes.', 'Fast repetition can hide a conceptual gap.', 'Choose one first-half weakness. Predict, attempt, explain, repair, and return tomorrow with a changed input. The published mock contains six challenges, not every assessed challenge.', 'Can you explain the same control in a different language or framework?', 'Recall → changed example → attempt → error category → delayed retry', 'https://cheatsheetseries.owasp.org/'),
 ('An answer with an evidence chain', 'For an original practice scenario, write the asset, attacker-controlled input, trust boundary, mechanism, impact and defense. End with a test whose result could show that the proposed defense is wrong. This structure improves a written explanation without revealing a graded answer.', 'Naming a vulnerability is only the beginning of the explanation.', 'Use a new scenario from your own notes. Write one paragraph, then underline the observation that supports each claim.', 'Which conclusion is unsupported if you only know an HTTP status code?', 'Scenario → evidence → causal explanation → defense → falsifiable test', 'https://owasp.org/www-project-web-security-testing-guide/'),
 ('Reproducible practical evidence', 'A successful attempt that omits the exact request is difficult to review. Keep the normal baseline, the changed request, the relevant response and the source explanation. A retest must also show that legitimate behavior still works.', 'A flag or screenshot alone does not explain the mechanism.', 'Rehearse on your assigned disposable target. Keep a timestamped record and a reproducible command; use the official seven-challenge brief for assessed scope.', 'What evidence distinguishes a fixed root cause from a payload blocked by accident?', 'Scope → baseline → one changed input → result → root cause → retest', 'https://owasp.org/www-project-web-security-testing-guide/'),
 ('Binding a privileged field', 'A registration endpoint copies every JSON field into its user object. A caller supplies is_admin=true. The defended variant chooses allowed fields and assigns privilege server-side. The exercise uses a toy identity header; production needs a verified identity before object-level policy runs.', 'Field filtering and object authorization are separate controls.', 'Try the same JSON against vulnerable and defended personal targets. Record which fields survive, then test the 401/403/200 object-access ladder.', 'How would multiple replicas change an in-process, per-IP rate limiter?', 'JSON → field allowlist → verified identity → ownership policy → stored state', 'https://owasp.org/API-Security/'),
 ('A borrowed address outlives storage', 'A program copies a pointer, frees the allocation and sets only the original pointer to NULL. The alias still contains the old address. AddressSanitizer identifies the later invalid access. Finish borrowing before release; separately check arithmetic before turning record counts into allocation sizes.', 'Changing one pointer does not update its aliases.', 'Run the optional ownership/allocation workshop. Explain both expected sanitizer reports and the normal inputs that still work after each repair.', 'How can asynchronous callbacks or FFI cause a lifetime to escape a local function?', 'Allocate → borrow → lifetime ends → stale access → diagnostic → repair', 'https://clang.llvm.org/docs/AddressSanitizer.html'),
 ('A signature needs an identity policy', 'A valid cryptographic signature from an unexpected signer does not satisfy your release policy. Bind verification to an immutable digest, exact expected identity and issuer. An SBOM lists components; provenance describes a build claim; neither alone proves that the software is safe.', 'Signed, inventoried and trustworthy are different claims.', 'Use the strict verifier against a learner-owned artifact. Test the expected identity and a wrong identity, and distinguish authentication/setup errors from a policy rejection.', 'Which build claims would you require before promoting the artifact to production?', 'Dependency source → build → immutable digest → signer policy → provenance decision', 'https://docs.sigstore.dev/cosign/verifying/verify/'),
 ('A private subnet is one layer', 'A container has no published port, but it may still reach a host bridge socket or metadata unless those paths are blocked. Trace ingress, DNS, forwarding and host INPUT rules separately. An IAM wildcard describes an authorization problem that network privacy does not repair.', 'Private addressing is not a complete isolation policy.', 'Use the IAM models and a local infrastructure scan. For the course environment, compare own-workspace success with cross-student, cross-team, host and metadata denial evidence.', 'How would an untrusted container attached to a proxy network change the attack surface?', 'VPN peer → gateway policy → fixed relay → private target → egress boundary', 'https://docs.docker.com/engine/network/drivers/bridge/'),
 ('Untrusted text asks for a tool', 'A document claims to be a system instruction and asks an assistant to run a privileged operation. Its wording cannot grant that authority. Tool policy, identity and capability boundaries must be enforced by application code. The lab chatbot is deterministic; the learning guide calls a real model with no tools.', 'A stronger prompt is not an authorization boundary.', 'Compare the two mock targets, then use the policy model to remove an unnecessary tool. Record benign behavior, an injection attempt and the enforced boundary.', 'How would you test indirect injection from a retrieved document without sending real secrets?', 'Untrusted content → model context → proposed action → independent policy → outcome', 'https://genai.owasp.org/llmrisk/llm01-prompt-injection/'),
 ('A failed check gets ignored', 'A pipeline runs a scanner but discards its exit status. The green job badge then measures command completion, not the desired security gate. Preserve failure signals and require the policy before promotion. Deployment and release approval are separate decisions.', 'Running a tool does not mean enforcing its result.', 'Toggle the release gates in the visual model, then compare fail-open and fail-closed personal services. Check an allowed administrator as well as denied requests.', 'What prevents a different workflow or stale artifact from bypassing the gate?', 'Change → tests/scan → enforced result → immutable artifact → authorized release', 'https://slsa.dev/spec/v1.2/'),
 ('A control belongs in an argument', 'Choose one NoteVault boundary and connect a threat to code, a defensive change and two tests. Explain the tradeoff and remaining risk. A portfolio of unrelated scanner screenshots does not provide that causal chain.', 'A capstone needs a coherent security argument.', 'Use a personal project target for rehearsal; keep your actual repository and evidence outside the disposable runtime. Practice the live demonstration and recovery path.', 'Which operational failure could invalidate a defense that passes its unit tests?', 'Threat → implementation → positive/negative tests → operational assumption → demonstration', 'https://owasp.org/www-project-application-security-verification-standard/'),
 ('Use the mock as a diagnostic', 'The eight-challenge mock and twelve-challenge final are different. A strong mock score does not establish coverage of missing written-design or DevSecOps topics. Use the mock to classify gaps, then choose separate evidence-based revision tasks.', 'Practice scope is not identical to final scope.', 'Build a revision matrix with topic, evidence, last error and next changed-input test. Include project and pipeline reasoning outside the mock.', 'Where does your revision plan rely on memorized inputs instead of transferable models?', 'Mock → observed gaps → missing coverage → focused repair → delayed recall', 'https://owasp.org/www-project-web-security-testing-guide/'),
 ('Defend a design under changed assumptions', 'A policy works for one server but the scenario adds replicas and concurrent requests. Re-examine shared state, ordering and identity rather than merely repeating the old control. Use the published written-exam scope to choose which concepts to explain.', 'A control inherits the assumptions of its design.', 'Write an original API, memory, supply-chain, cloud or AI scenario. Change one assumption and explain whether the defense still holds.', 'What measurement or experiment would distinguish your two competing explanations?', 'Assumption → security property → changed system → counterexample → revised design', 'https://owasp.org/www-project-application-security-verification-standard/'),
 ('Hand over evidence that survives you', 'The final includes practical work and capstone handover. Another person should be able to identify the tested version, reproduce the setup, verify a defense and follow the rollback steps. Record the presentation before the session and prepare for the short Q&A described in the official brief.', 'A polished demo is not a reproducible handover.', 'Rehearse from a clean checkout with your own practice data. Link the evidence to the tested version; use instructor materials for actual deadlines and assessment rules.', 'What would a maintainer need if you were unavailable during an incident?', 'Version → reproducible setup → evidence → demonstration → rollback → handover', 'https://slsa.dev/spec/v1.2/'),
]


def week(number):
    title, example, misconception, practice, stretch, sequence, reference = CASES[number - 1]
    return {'title': title, 'example': example, 'misconception': misconception, 'practice': practice,
            'stretch': stretch, 'stages': sequence.split(' → '), 'reference': reference,
            'labs': {key: value for key, value in LABS.items() if value['week'] == number}}
